QDRANT_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.8JXrvAv1IREdUk0E5s02zmgzfRLBMzF8Q6SbZk8Iyj8"
QDRANT_URL = "https://63ed5e76-957a-4631-9c5b-31ddf74939bb.eu-west-2-0.aws.cloud.qdrant.io:6333"